from __future__ import annotations

from abc import ABC, abstractmethod
from collections.abc import Sequence

from src.domain import Fill, Order, Position


class ExecutionEngine(ABC):
    """
    Abstract execution interface.

    Converts strategy-approved orders into execution results.

    Implementations may represent:
        - historical backtest execution
        - paper trading execution
        - live broker execution

    Strategy logic must remain completely unaware of the concrete
    execution implementation.
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """Return the execution engine name."""

    @property
    @abstractmethod
    def mode(self) -> str:
        """Return the execution mode identifier."""

    @abstractmethod
    def submit_order(self, order: Order) -> Sequence[Fill]:
        """
        Submit an order and return resulting fills.

        Implementations are responsible for translating an Order into the
        appropriate execution behavior for their environment.
        """

    @abstractmethod
    def cancel_order(self, order_id: str) -> bool:
        """
        Cancel an outstanding order.

        Returns True when the cancellation request was accepted.
        """

    @abstractmethod
    def get_position(self, symbol: str) -> Position | None:
        """Return the current position for a symbol, if one exists."""

    @abstractmethod
    def close_position(self, symbol: str) -> Sequence[Fill]:
        """
        Close the current position for a symbol.

        Returns the fills generated by the closing operation.
        """
